/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    application
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.org.ow2.asm.asm)
    api(libs.org.ow2.asm.asm.tree)
    api(libs.org.antlr.antlr4)
    api(libs.org.assertj.assertj.core)
}

group = "io.github.tjfacos"
version = "1.0-SNAPSHOT"
description = "fearnlang"

java {
    sourceCompatibility = JavaVersion.VERSION_23
    targetCompatibility = JavaVersion.VERSION_23
}

application {
    mainClass.set("io.github.tjfacos.FearnC")
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
